//go:build generate
// +build generate

package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"io"
	"log"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"text/tabwriter"
)

func init() {
	log.SetFlags(log.Lshortfile)
}

// Some stdlib packages share the same name, exclude is used to
// pick which of the two we ignore.
//
// import path => preferred import path
var exclude = map[string]string{
	"go/scanner":     "text/scanner",
	"text/template":  "html/template",
	"net/http/pprof": "runtime/pprof",
	"crypto/rand":    "math/rand",
}

func printExclude(w io.Writer) {
	keys := make([]string, 0, len(exclude))
	for k := range exclude {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	tw := tabwriter.NewWriter(w, 1, 1, 1, ' ', 0)
	for _, k := range keys {
		fmt.Fprintf(tw, "// %q:\t%q,\t// prefer: %s\n", path.Base(k), k, exclude[k])
	}
	if err := tw.Flush(); err != nil {
		log.Fatal(err)
	}
}

func writeStdlib(data []byte) {
	tmp, err := os.CreateTemp(".", "stdlib.go.*")
	if err != nil {
		log.Fatal(err)
	}
	fatal := func(err error) {
		tmp.Close()
		os.Remove(tmp.Name())
		log.Output(2, fmt.Sprint(err))
		os.Exit(1)
	}
	if err := tmp.Chmod(0644); err != nil {
		fatal(err)
	}
	if _, err := tmp.Write(data); err != nil {
		fatal(err)
	}
	if err := tmp.Close(); err != nil {
		fatal(err)
	}
	if err := os.Rename(tmp.Name(), "stdlib.go"); err != nil {
		fatal(err)
	}
}

func main() {
	dryRun := flag.Bool("dry-run", false, "print output")
	flag.Parse()

	root := filepath.Join(runtime.GOROOT(), "src")
	if fi, err := os.Stat(root); err != nil || !fi.IsDir() {
		log.Fatal("GOROOT:", err)
	}

	cmd := exec.Command("go", "list", "./...")
	cmd.Dir = root
	cmd.Stderr = os.Stderr
	rc, err := cmd.StdoutPipe()
	if err != nil {
		log.Fatal(err)
	}
	if err := cmd.Start(); err != nil {
		log.Fatal(err)
	}

	ignoreRe := regexp.MustCompile(`(?m)(^|/)(cmd|internal)($|/)`)

	type Package struct {
		Name, ImportPath string
	}
	var pkgs []Package
	scanner := bufio.NewScanner(rc)
	for scanner.Scan() {
		s := scanner.Text()
		if s == "" || ignoreRe.MatchString(s) {
			continue
		}
		if _, ok := exclude[s]; ok {
			continue
		}
		pkgs = append(pkgs, Package{
			Name:       path.Base(s),
			ImportPath: s,
		})
	}
	if err := scanner.Err(); err != nil {
		log.Fatal(err)
	}
	if err := cmd.Wait(); err != nil {
		log.Fatal(err)
	}

	sort.Slice(pkgs, func(i, j int) bool {
		return pkgs[i].Name < pkgs[j].Name
	})
	sort.SliceStable(pkgs, func(i, j int) bool {
		return pkgs[i].ImportPath < pkgs[j].ImportPath
	})

	w := new(bytes.Buffer)
	const header = `// Code generated by genstdlib.go; DO NOT EDIT.
// go version: %s

package suggest

var knownPackageIdents = map[string]string{
`
	fmt.Fprintf(w, header, runtime.Version())
	for _, p := range pkgs {
		fmt.Fprintf(w, "\t%q: %q,\n", p.Name, p.ImportPath)
	}
	fmt.Fprint(w, "\n")
	printExclude(w)
	fmt.Fprintln(w, "}")

	src, err := format.Source(w.Bytes())
	if err != nil {
		log.Fatal(err)
	}

	if *dryRun {
		if _, err := os.Stdout.Write(src); err != nil {
			log.Fatal(err)
		}
		return
	}

	writeStdlib(src)
}
