//go:build generate
// +build generate

package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
)

func init() {
	log.SetFlags(log.Lshortfile)
}

func writeStdlib(data []byte) {
	tmp, err := os.CreateTemp(".", "stdlib.go.*")
	if err != nil {
		log.Fatal(err)
	}
	fatal := func(err error) {
		tmp.Close()
		os.Remove(tmp.Name())
		log.Output(2, fmt.Sprint(err))
		os.Exit(1)
	}
	if err := tmp.Chmod(0644); err != nil {
		fatal(err)
	}
	if _, err := tmp.Write(data); err != nil {
		fatal(err)
	}
	if err := tmp.Close(); err != nil {
		fatal(err)
	}
	if err := os.Rename(tmp.Name(), "stdlib.go"); err != nil {
		fatal(err)
	}
}

func main() {
	dryRun := flag.Bool("dry-run", false, "print output")
	flag.Parse()

	root := filepath.Join(runtime.GOROOT(), "src")
	if fi, err := os.Stat(root); err != nil || !fi.IsDir() {
		log.Fatal("GOROOT:", err)
	}

	cmd := exec.Command("go", "list", "./...")
	cmd.Dir = root
	cmd.Stderr = os.Stderr
	rc, err := cmd.StdoutPipe()
	if err != nil {
		log.Fatal(err)
	}
	if err := cmd.Start(); err != nil {
		log.Fatal(err)
	}

	ignoreRe := regexp.MustCompile(`(?m)(^|/)(cmd|internal)($|/)`)

	type Package struct {
		Name, ImportPath string
	}
	var pkgs []string
	scanner := bufio.NewScanner(rc)
	for scanner.Scan() {
		s := scanner.Text()
		if s == "" || ignoreRe.MatchString(s) {
			continue
		}
		pkgs = append(pkgs, s)
	}
	if err := scanner.Err(); err != nil {
		log.Fatal(err)
	}
	if err := cmd.Wait(); err != nil {
		log.Fatal(err)
	}

	sort.Strings(pkgs)

	w := new(bytes.Buffer)
	const header = `// Code generated by genstdlib.go; DO NOT EDIT.
// go version: %s

package cache

func isStdLibPkg(path string) bool {
	_, ok := knownStdLibPkgs[path]
	return ok
}

var knownStdLibPkgs = map[string]struct{}{
`
	fmt.Fprintf(w, header, runtime.Version())
	for _, p := range pkgs {
		fmt.Fprintf(w, "\t%q: {},\n", p)
	}
	fmt.Fprint(w, "\n")
	fmt.Fprintln(w, "}")

	src, err := format.Source(w.Bytes())
	if err != nil {
		log.Fatal(err)
	}

	if *dryRun {
		if _, err := os.Stdout.Write(src); err != nil {
			log.Fatal(err)
		}
		return
	}

	writeStdlib(src)
}
